name: CTest Action
description: Test your CMake project with CTest
author: Alfi Maulana
branding:
  color: gray-dark
  icon: terminal
runs:
  using: composite
  steps:
    - name: Test the CMake project
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: ctest --test-dir build --output-on-failure --no-tests=error
