name: CTest Action
author: Alfi Maulana
description: Test your CMake project with CTest
branding:
  icon: terminal
  color: gray-dark
inputs:
  args:
    description: Additional arguments to pass during the CTest run
runs:
  using: composite
  steps:
    - name: Test the CMake project
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: ctest --test-dir build --output-on-failure --no-tests=error ${{ inputs.args }}
