name: CTest Action
author: Alfi Maulana
description: Test CMake projects using CTest
branding:
  icon: terminal
  color: gray-dark
inputs:
  test-dir:
    description: Specifies the directory in which to look for tests
    default: build
  build-config:
    description: Chooses the configuration to test
  tests-regex:
    description: Runs tests matching the regular expression
  verbose:
    description: Enable verbose output from tests
  args:
    description: Additional arguments to pass during the CTest run
runs:
  using: node20
  main: dist/main.bundle.mjs
