name: CTest Action
author: Alfi Maulana
description: Test your CMake project with CTest
branding:
  icon: terminal
  color: gray-dark
inputs:
  test-dir:
    description: Specifies the directory in which to look for tests
    default: build
  build-config:
    description: Choose the configuration to test
  tests-regex:
    description: Run tests matching regular expression
  args:
    description: Additional arguments to pass during the CTest run
runs:
  using: composite
  steps:
    - name: Test the CMake project
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: ctest --test-dir '${{ inputs.test-dir }}'${{ inputs.build-config && format(' --build-config ''{0}''', inputs.build-config) }}${{ inputs.tests-regex && format(' --tests-regex ''{0}''', inputs.tests-regex) }} --output-on-failure --no-tests=error ${{ inputs.args }}
