name: test
on:
  workflow_dispatch:
  pull_request:
    branches: ['*', '!latest']
  push:
    branches: [latest, main]
jobs:
  default-usage:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.2

      - name: Move the test project to the working directory
        run: mv test/* .

      - name: Configure and build the project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true

      - name: Use the action
        uses: ./
        with:
          args: ${{ matrix.os == 'windows' && '-C Debug' || '' }}
